import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableFooter,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import React from "react";

export const invoices = [
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV001",
        paymentStatus: "Paid",
        totalAmount: "$250.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV002",
        paymentStatus: "Pending",
        totalAmount: "$150.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV003",
        paymentStatus: "Unpaid",
        totalAmount: "$350.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV004",
        paymentStatus: "Paid",
        totalAmount: "$450.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV005",
        paymentStatus: "Paid",
        totalAmount: "$550.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV006",
        paymentStatus: "Pending",
        totalAmount: "$200.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV007",
        paymentStatus: "Unpaid",
        totalAmount: "$300.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV008",
        paymentStatus: "Paid",
        totalAmount: "$600.00",
        paymentMethod: "Credit Card",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV009",
        paymentStatus: "Pending",
        totalAmount: "$220.00",
        paymentMethod: "PayPal",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
    {
        invoice: "INV010",
        paymentStatus: "Unpaid",
        totalAmount: "$400.00",
        paymentMethod: "Bank Transfer",
        additionalInfo1: "Extra Data 1",
        additionalInfo2: "More Details 2",
        additionalInfo3: "Further Information 3",
        additionalInfo4: "Yet Another Detail 4",
    },
];

export default function TableDemo() {
    return (
        <div className="overflow-auto">
            <Table>
                <TableCaption>A list of your recent invoices.</TableCaption>
                <TableHeader>
                    <TableRow>
                        <TableHead className="w-[100px]">Invoice</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Method</TableHead>
                        <TableHead>Info 1</TableHead>
                        <TableHead>Info 2</TableHead>
                        <TableHead>Info 3</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead>Info 4</TableHead>
                        <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {invoices.map((invoice) => (
                        <TableRow key={invoice.invoice}>
                            <TableCell className="font-medium">{invoice.invoice}</TableCell>
                            <TableCell>{invoice.paymentStatus}</TableCell>
                            <TableCell>{invoice.paymentMethod}</TableCell>
                            <TableCell>{invoice.additionalInfo1}</TableCell>
                            <TableCell>{invoice.additionalInfo2}</TableCell>
                            <TableCell>{invoice.additionalInfo3}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell>{invoice.additionalInfo4}</TableCell>
                            <TableCell className="text-right">{invoice.totalAmount}</TableCell>
                        </TableRow>
                    ))}
                </TableBody>
                <TableFooter>
                    <TableRow>
                        <TableCell colSpan={7}>Total</TableCell>
                        <TableCell className="text-right">$3,020.00</TableCell>
                    </TableRow>
                </TableFooter>
            </Table>
        </div>
    );
}